POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphcmVka2xvcHN0ZWluIiwiaWQiOiI2NDJiMTc4NTBiYjdhNTU1MGZhY2NkYWIiLCJpYXQiOjE2ODA1NTE3NjR9.Ww8Z7gRVXTWrWH9awYcc2x1df8_ADoXY1mhpMtKEImA

{
  "title": "Testing section 4",
  "author": "Jared Klopstein",
  "url": "jaredklopstein.com/blog/example",
  "likes": 4,
  "userId": "642aefae383895510fe20285"
}